# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%env(MEDIA_FOLDER)%'
    filesystems:
        music:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem
